/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba2modulo2;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author aldoa
 */
public class Pasajero extends javax.swing.JFrame {
    Connection conexion = Conexion.getConnection();
    String nombre, rut, codigoReserva;
    int[] idVuelos = new int[10];
    int idVueloSeleccionado=0;
    /**
     * Creates new form Pasajeros
     */
    public Pasajero() {
        initComponents();
        llenarComboBoxVuelos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        rutTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        apellidoTextField = new javax.swing.JTextField();
        direccionTextField = new javax.swing.JTextField();
        telefonoTextField = new javax.swing.JTextField();
        sexoTextField = new javax.swing.JTextField();
        vuelosComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        codigoReservaTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        asientosDisponiblesLabel = new javax.swing.JLabel();
        volverPasajeroButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Información Vuelo");

        jLabel2.setText("Rut ");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Dirección");

        jLabel6.setText("Telefono");

        jLabel7.setText("Sexo");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Información Pasajero");

        rutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutTextFieldActionPerformed(evt);
            }
        });

        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        vuelosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vuelosComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setText("Vuelos");

        jLabel10.setText("CodigoReserva");

        codigoReservaTextField.setEditable(false);
        codigoReservaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoReservaTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Asientos disponibles");

        volverPasajeroButton.setText("Volver");
        volverPasajeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverPasajeroButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Generar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(volverPasajeroButton)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(asientosDisponiblesLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreTextField)
                                    .addComponent(apellidoTextField)
                                    .addComponent(direccionTextField)
                                    .addComponent(telefonoTextField)
                                    .addComponent(rutTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(codigoReservaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(sexoTextField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(vuelosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(apellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sexoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoReservaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vuelosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(asientosDisponiblesLabel))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(volverPasajeroButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rutTextFieldActionPerformed

    private void volverPasajeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverPasajeroButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_volverPasajeroButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                validarFormulario();
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void codigoReservaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoReservaTextFieldActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_codigoReservaTextFieldActionPerformed

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        generarCodigoReserva();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void vuelosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vuelosComboBoxActionPerformed
        // TODO add your handling code here:
        int numIdVuelo;
        String asientos="";
        ResultSet resultSet;
        numIdVuelo = vuelosComboBox.getSelectedIndex();
        idVueloSeleccionado = numIdVuelo;
           try {
               resultSet = Controlador.obtenerAsientosDisponibles(conexion, idVuelos[numIdVuelo]);
               resultSet.next();
               asientos = resultSet.getObject("cantidadAsientos").toString();
           } catch (SQLException ex) {
               
           }
           asientosDisponiblesLabel.setText(asientos);
    }//GEN-LAST:event_vuelosComboBoxActionPerformed

    
    public void generarCodigoReserva() {
            rut = rutTextField.getText();
            nombre = nombreTextField.getText();
            if (!rut.isEmpty() & rut.length()>3 & !nombre.isEmpty() & nombre.length()>3) {
                    codigoReserva = rut.substring(0,3)+nombre.substring(0,3);

                    codigoReservaTextField.setText(codigoReserva);  
            } else {
                JOptionPane.showMessageDialog(null, "Ingresar rut y nombre para generar Código de Reserva");
            }
            
    }
    
    public void llenarComboBoxVuelos(){
        try {
            ResultSet resultSet = Controlador.obtenerVuelos(conexion);
            int i = 0;
            while(resultSet.next()) {
                String vuelo;
                idVuelos[i] = Integer.valueOf(resultSet.getObject("idVuelo").toString());
                vuelo = ("Vuelo: "+resultSet.getObject("idVuelo").toString()+"| "+resultSet.getObject("origen").toString()+"->"+resultSet.getObject("destino"));
                vuelosComboBox.addItem(vuelo);
                i = i+1;
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    public void validarFormulario() {
        Viajero viajero = Viajero.getInstance();
        int idVuelo;
        String apellido, direccion, telefono, sexo;
        boolean isNull;


        rut = rutTextField.getText();
        
            if(!rut.isEmpty()){
                if (isInteger(rut)) {
                    viajero.setRut(Integer.valueOf(rut));
                } else {
                    JOptionPane.showMessageDialog(null, "Ingresar solo números en el rut");
                    rut = "";
                    rutTextField.setText(rut);
                }     
            }
        
        nombre = nombreTextField.getText();
        
            if(!nombre.isEmpty()) {
                viajero.setNombre(nombre);
            }

        apellido = apellidoTextField.getText();
        
            if(!apellido.isEmpty()) {
                viajero.setApellido(apellido);
            }
        
        direccion = direccionTextField.getText();
            if(!direccion.isEmpty()) {
                viajero.setDireccion(direccion);
            }
            
        telefono = telefonoTextField.getText();
            if(!telefono.isEmpty()) {
                if(isInteger(telefono)) {
                    viajero.setTelefono(Integer.valueOf(telefono));
                } else {
                    JOptionPane.showMessageDialog(null, "Ingresar solo números en el teléfono");
                    telefono = "";
                    telefonoTextField.setText(telefono);
                }    
            }
        
        sexo = sexoTextField.getText();
            if(!sexo.isEmpty()) {
                viajero.setSexo(sexo.charAt(0));
            } 
            if (sexo.length()>1) {
                JOptionPane.showMessageDialog(null, "Ingresar solo F o M en Sexo");
                sexo = "";
                sexoTextField.setText(sexo);
            }
        
        if (!rut.isEmpty() & rut.length()>3 & !nombre.isEmpty() & nombre.length()>3) {
            codigoReserva = rut.substring(0,3)+nombre.substring(0,3);
            codigoReservaTextField.setText(codigoReserva);
                if (!codigoReserva.isEmpty() | codigoReserva.length()>=6) {
                    viajero.setCodigoReserva(codigoReserva);
                }
        }
        
        idVuelo = idVuelos[idVueloSeleccionado];
        
        viajero.setIdVuelo(idVuelo);
        System.out.println(idVuelo);
        
        isNull = (rut.equals("") | nombre.equals("") | apellido.equals("") | direccion.equals("") | telefono.equals("") | sexo.equals("") | codigoReserva.equals(""));
        
        if (isNull) {
            JOptionPane.showMessageDialog(null,"Faltan datos del pasajero para completar la reserva");
        } else {
            Controlador.insertarPasajero(conexion, viajero);
            clearForms();
        }
        
       
        
    }
    
    public void clearForms() {
        rutTextField.setText("");
        nombreTextField.setText("");
        apellidoTextField.setText("");
        direccionTextField.setText("");
        telefonoTextField.setText("");
        sexoTextField.setText("");
        codigoReservaTextField.setText("");
    }
        
    public boolean isInteger(String string) {
            try {
                Integer.valueOf(string);
                return true;
            } catch (NumberFormatException e) {
                return false;
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pasajero().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoTextField;
    private javax.swing.JLabel asientosDisponiblesLabel;
    private javax.swing.JTextField codigoReservaTextField;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField rutTextField;
    private javax.swing.JTextField sexoTextField;
    private javax.swing.JTextField telefonoTextField;
    private javax.swing.JButton volverPasajeroButton;
    private javax.swing.JComboBox vuelosComboBox;
    // End of variables declaration//GEN-END:variables
}
